---
- hosts: localhost
  name: Gather Facts
  tasks:
  - name: "Mapping a lun"
    netapp.ontap.na_ontap_lun_map:
      state: present
      hostname: "{{ morpheus ['customOptions']['jk_cluster']  }}"
      username: "{{ morpheus ['customOptions']['jk_username']  }}"
      password: "{{ morpheus ['customOptions']['jk_password']  }}"
      initiator_group_name: "{{ morpheus ['customOptions']['jk_igroup']  }}"
      path: "{{ morpheus ['customOptions']['jk_lunpath'] }}"
      vserver: "{{ morpheus ['customOptions']['jk_vserver']  }}"
      https: true
      validate_certs: false

  