---
- hosts: localhost
  name: Gather Facts
  tasks:
  - name: Sending an e-mail
    community.general.mail:
     host: relay.astrazeneca.net
     port: 25
     to: thangakameshwaran.jayapaul@astrazeneca.com
     subject: Ansible-report
     body: System has been successfully provisioned.
    delegate_to: localhost