---
- hosts: localhost
  tasks:  
   - name: Create FlexVol
     netapp.ontap.na_ontap_volume:
      state: present
      name: "{{ morpheus ['customOptions']['jk_volname'] }}"
      is_infinite: False
      aggregate_name: "{{ morpheus ['customOptions']['jk_aggrname']  }}"
      size: "{{ morpheus ['customOptions']['jk_size']  }}"
      size_unit: gb
      user_id: 1001
      group_id: 2002
      tiering_policy: auto
      export_policy: default
      junction_path: "{{ morpheus ['customOptions']['jk_volname'] }}"
      percent_snapshot_space: 5
      vserver: "{{ morpheus ['customOptions']['jk_vserver']  }}"
      wait_for_completion: True
      nvfail_enabled: False
      comment: "{{ morpheus ['customOptions']['jk_request']  }}"
      hostname: "{{ morpheus ['customOptions']['jk_cluster']  }}"
      username: "{{ morpheus ['customOptions']['jk_username']  }}"
      password: "{{ morpheus ['customOptions']['jk_password']  }}"
     register: volcreate 

   - name: Sending an e-mail
     community.general.mail:
      host: relay.astrazeneca.net
      port: 25
      from: thangakameshwaran.jayapaul@astrazeneca.com
      to: thangakameshwaran.jayapaul@astrazeneca.com
      subject: "{{ansible_play_name}} has completed"
      body: "Here are the results {{ volcreate}}"
  